# Generated by Django 5.2 on 2025-07-21 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='votes',
        ),
        migrations.AddField(
            model_name='votereponse',
            name='valeur',
            field=models.SmallIntegerField(choices=[(1, '👍 vote positif'), (-1, '👎 vote négatif')], default=1),
        ),
        migrations.AlterField(
            model_name='votereponse',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_recu', to='questions.reponse'),
        ),
        migrations.DeleteModel(
            name='VoteQuestion',
        ),
    ]
