# Generated by Django 5.2 on 2025-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_votes_remove_reponse_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='votereponse',
            name='valeur',
            field=models.SmallIntegerField(choices=[(1, '👍'), (-1, '👎')], default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions_associees', to='questions.tag'),
        ),
    ]
